language: php

addons:
  apt:
    packages:
      - parallel
  sonarcloud:
    organization: "ichhabrecht-github"
    branches:
      - master
      - pre-merge

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache

jdk:
  - oraclejdk8

sudo: required

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

install:
  - >
    if [[ "$TYPO3" = *"dev"* ]]; then
      composer config minimum-stability dev;
      composer config prefer-stable true;
      composer require typo3/cms-core:"@dev" --no-update;
    fi
  - composer require typo3/cms:"$TYPO3"
  - mkdir -p .Build/public/typo3conf/ext/
  - if [ ! -L .Build/public/typo3conf/ext/filefill ]; then ln -snvf ../../../../. .Build/public/typo3conf/ext/filefill; fi
  - export TYPO3_PATH_ROOT=$PWD/.Build/public
  - export typo3DatabaseName=typo3
  - export typo3DatabaseHost=localhost
  - export typo3DatabaseUsername=root
  - export typo3DatabasePassword=

script:
  - >
    if [ -d "Tests/Unit" ]; then
      echo;
      echo "Running unit tests";
      echo;
      echo;
      .Build/bin/phpunit --bootstrap .Build/vendor/nimut/testing-framework/res/Configuration/UnitTestsBootstrap.php Tests/Unit/;
    fi

  - >
    if [ -d "Tests/Functional" ]; then
      echo;
      echo "Running functional tests";
      echo;
      echo;
      find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --bootstrap .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTestsBootstrap.php {}';
    fi

  - >
    echo;
    echo "Running php lint";
    echo;
    echo;
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;

jobs:
  fast_finish: true
  include:
    - stage: test
      php: 5.6
      env: TYPO3=^6.2
    - stage: test
      php: 5.5
      env: TYPO3=^6.2
    - stage: test
      php: 5.4
      env: TYPO3=^6.2
    - stage: test
      php: 5.3
      env: TYPO3=^6.2
      dist: precise
