dist: xenial

language: php

addons:
    apt:
        packages:
            - parallel
    sonarcloud:
        organization: "ichhabrecht-github"

cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/.sonar/cache

jdk:
    - oraclejdk8

services:
    - mysql

jobs:
    fast_finish: true
    allow_failures:
        -   if: type != cron
            env: TYPO3=dev-master
        -   if: type != cron
            env: TYPO3=9.5.x-dev
        -   if: type != cron
            env: TYPO3=8.7.x-dev
    include:
        - &tests
            stage: 🏃 tests
            before_install:
                - if php -i | grep -v TRAVIS_CMD | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
            install:
                - composer require --no-progress --no-suggest nimut/typo3-complete:"$TYPO3"
                - git checkout composer.json
            before_script:
                - mkdir -p .Build/public/typo3conf/ext/
                - if [ ! -L .Build/public/typo3conf/ext/filefill ]; then ln -snvf ../../../../. .Build/public/typo3conf/ext/filefill; fi
                - export TYPO3_PATH_ROOT=$PWD/.Build/public
                - export typo3DatabaseName=typo3
                - export typo3DatabaseHost=localhost
                - export typo3DatabaseUsername=root
                - export typo3DatabasePassword=
            script:
                - >
                    if [ -d "Tests/Unit" ]; then
                        echo;
                        echo "Running unit tests";
                        echo;
                        echo;
                        .Build/bin/phpunit --bootstrap .Build/vendor/nimut/testing-framework/res/Configuration/UnitTestsBootstrap.php --testsuite unit;
                    fi

                - >
                    if [ -d "Tests/Functional" ]; then
                        echo;
                        echo "Running functional tests";
                        echo;
                        echo;
                        find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --bootstrap .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTestsBootstrap.php {}';
                    fi

                - >
                    echo;
                    echo "Running php lint";
                    echo;
                    echo;
                    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;
            php: 7.4
            env: TYPO3=~10.3.0
        -   <<: *tests
            php: 7.4
            env: TYPO3=^9.5
        -   <<: *tests
            php: 7.3
            env: TYPO3=~10.3.0
        -   <<: *tests
            php: 7.3
            env: TYPO3=^9.5
        -   <<: *tests
            php: 7.3
            env: TYPO3=^8.7
        -   <<: *tests
            php: 7.2
            env: TYPO3=~10.3.0
        -   <<: *tests
            php: 7.2
            env: TYPO3=^9.5
        -   <<: *tests
            php: 7.2
            env: TYPO3=^8.7
        -   <<: *tests
            php: 7.1
            env: TYPO3=^8.7
        -   <<: *tests
            php: 7.0
            env: TYPO3=^8.7

        -   stage: 🚢 to ter
            if: tag IS present AND env(TYPO3_ORG_USERNAME) IS present AND env(TYPO3_ORG_PASSWORD) IS present
            php: 7.0
            script:
                - >
                    echo;
                    echo "Preparing upload of release ${TRAVIS_TAG} to TER";
                    echo;
                    echo;
                    composer global require helhum/ter-client;

                - >
                    TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`;
                    echo;
                    echo "Uploading release ${TRAVIS_TAG} to TER";
                    echo;
                    echo;
                    $HOME/.composer/vendor/bin/ter-client upload filefill . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE";

        -   stage: ✔ with sonarqube scanner
            if: type = push AND branch IN (master, pre-merge) AND env(SONAR_TOKEN) IS present AND fork = false
            git:
                depth: false
            php: 7.2
            env: TYPO3="^8.7 ^9.5 ~10.3.0"
            before_script:
                - mkdir -p .Log/coverage/ .Log/junit/
                - export TYPO3_PATH_WEB=$PWD/.Build/public
                - export typo3DatabaseName=typo3
                - export typo3DatabaseHost=localhost
                - export typo3DatabaseUsername=root
                - export typo3DatabasePassword=
            script:
                - >
                    if [ -d "Tests" ]; then
                        for TYPO3 in $TYPO3; do

                            echo;
                            echo "Running TYPO3 version $TYPO3";
                            echo;
                            echo;
                            git clean -Xdf;
                            composer require --dev --no-progress --no-suggest nimut/typo3-complete:"$TYPO3";
                            git checkout composer.json;
                            VERSION=${TYPO3//[!0-9]/};

                            mkdir -p .Build/public/typo3conf/ext/
                            if [ ! -L .Build/public/typo3conf/ext/filefill ]; then ln -snvf ../../../../. .Build/public/typo3conf/ext/filefill; fi

                            if [ -d "Tests/Unit" ]; then
                              echo;
                              echo "Running unit tests";
                              echo;
                              echo;
                              .Build/bin/phpunit --bootstrap .Build/vendor/nimut/testing-framework/res/Configuration/UnitTestsBootstrap.php --log-junit .Log/junit/unit_$VERSION.xml --coverage-php .Log/coverage/unit_$VERSION.cov  --testsuite unit;
                            fi

                            if [ -d "Tests/Functional" ]; then
                              echo;
                              echo "Running functional tests";
                              echo;
                              echo;
                              .Build/bin/phpunit --bootstrap .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTestsBootstrap.php --log-junit .Log/junit/functional_$VERSION.xml --coverage-php .Log/coverage/functional_$VERSION.cov --testsuite functional;
                            fi
                        done

                        echo;
                        echo "Merging log and coverage files";
                        echo;
                        echo;
                        composer require --no-progress --no-suggest --update-with-all-dependencies nimut/phpunit-merger;
                        .Build/bin/phpunit-merger coverage .Log/coverage/ .Log/coverage.xml;
                        .Build/bin/phpunit-merger log .Log/junit/ .Log/junit.xml;
                    fi

                - >
                    echo;
                    echo "Running SonarQube Scanner";
                    echo;
                    echo;
                    sonar-scanner;

        - &dev-tests
            <<: *tests
            stage: 🏃 dev tests
            before_install:
                - if php -i | grep -v TRAVIS_CMD | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
                - composer config minimum-stability dev
                - composer config prefer-stable true
                - composer require --no-progress --no-suggest --no-update typo3/cms-core:"@dev"
            php: 7.4
            env: TYPO3=dev-master
        -   <<: *dev-tests
            php: 7.4
            env: TYPO3=9.5.x-dev
        -   <<: *dev-tests
            php: 7.3
            env: TYPO3=dev-master
        -   <<: *dev-tests
            php: 7.3
            env: TYPO3=9.5.x-dev
        -   <<: *dev-tests
            php: 7.3
            env: TYPO3=8.7.x-dev
        -   <<: *dev-tests
            php: 7.2
            env: TYPO3=dev-master
        -   <<: *dev-tests
            php: 7.2
            env: TYPO3=9.5.x-dev
        -   <<: *dev-tests
            php: 7.2
            env: TYPO3=8.7.x-dev
        -   <<: *dev-tests
            php: 7.1
            env: TYPO3=8.7.x-dev
        -   <<: *dev-tests
            php: 7.0
            env: TYPO3=8.7.x-dev

        - &lowest-tests
            <<: *dev-tests
            stage: 🏃 prefer-lowest tests
            if: type = cron
            install:
                - composer require --no-progress --no-suggest --no-update typo3/cms-composer-installers:"^1.5 || ^2.0"
                - composer require --no-progress --no-suggest --prefer-lowest nimut/typo3-complete:"$TYPO3"
                - git checkout composer.json
            php: 7.4
            env: TYPO3=dev-master
        -   <<: *lowest-tests
            php: 7.4
            env: TYPO3=^9.5
        -   <<: *lowest-tests
            php: 7.4
            env: TYPO3=9.5.x-dev
        -   <<: *lowest-tests
            php: 7.3
            env: TYPO3=dev-master
        -   <<: *lowest-tests
            php: 7.3
            env: TYPO3=^9.5
        -   <<: *lowest-tests
            php: 7.3
            env: TYPO3=9.5.x-dev
        -   <<: *lowest-tests
            php: 7.3
            env: TYPO3=^8.7
        -   <<: *lowest-tests
            php: 7.3
            env: TYPO3=8.7.x-dev
        -   <<: *lowest-tests
            php: 7.2
            env: TYPO3=dev-master
        -   <<: *lowest-tests
            php: 7.2
            env: TYPO3=^9.5
        -   <<: *lowest-tests
            php: 7.2
            env: TYPO3=9.5.x-dev
        -   <<: *lowest-tests
            php: 7.2
            env: TYPO3=^8.7
        -   <<: *lowest-tests
            php: 7.2
            env: TYPO3=8.7.x-dev
        -   <<: *lowest-tests
            php: 7.1
            env: TYPO3=^8.7
        -   <<: *lowest-tests
            php: 7.1
            env: TYPO3=8.7.x-dev
        -   <<: *lowest-tests
            php: 7.0
            env: TYPO3=^8.7
        -   <<: *lowest-tests
            php: 7.0
            env: TYPO3=8.7.x-dev
